name: Publish
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm version
        run: npm version ${{ github.ref }} --no-git-tag-version
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo bump
        run: cargo install cargo-bump
      - name: Update cargo version
        run: cargo bump ${{ github.ref }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: bump version'
          branch: ${{ github.ref }}

  publish_npm:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GBPROD_GITCOMMIT }}

  publish_crates:
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_GBPROD_GITCOMMIT }}
